# Import Libraries:

In [1]:
import pandas as pd 
import seaborn as sns 
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

# Using Scikit-Learn for Iris classification 

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load iris dataset:

In [3]:
iris = load_iris()
data = iris.data
target = iris.target

In [4]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [5]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# Data splitting  

In [6]:
x_train,x_test,y_train,y_test = train_test_split(data,target,test_size=0.25,random_state=42)

In [7]:
model=LogisticRegression()

In [8]:
model.fit(x_train,y_train)

C:\Users\NISHANT\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [9]:
y_pred = model.predict(x_test)
accuracy =accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 1.0


# Using Tensorflow for Iris classification 

In [10]:
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [12]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(x_train_scaled.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [13]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [14]:
model.fit(x_train_scaled, y_train, epochs=100, batch_size=32, verbose=2)

Epoch 1/100
4/4 - 0s - loss: 0.6487 - accuracy: 0.2946 - 489ms/epoch - 122ms/step
Epoch 2/100
4/4 - 0s - loss: 0.6373 - accuracy: 0.3036 - 5ms/epoch - 1ms/step
Epoch 3/100
4/4 - 0s - loss: 0.6260 - accuracy: 0.3125 - 14ms/epoch - 3ms/step
Epoch 4/100
4/4 - 0s - loss: 0.6148 - accuracy: 0.3304 - 18ms/epoch - 4ms/step
Epoch 5/100
4/4 - 0s - loss: 0.6032 - accuracy: 0.3304 - 17ms/epoch - 4ms/step
Epoch 6/100
4/4 - 0s - loss: 0.5919 - accuracy: 0.3482 - 17ms/epoch - 4ms/step
Epoch 7/100
4/4 - 0s - loss: 0.5810 - accuracy: 0.3482 - 10ms/epoch - 3ms/step
Epoch 8/100
4/4 - 0s - loss: 0.5694 - accuracy: 0.3661 - 15ms/epoch - 4ms/step
Epoch 9/100
4/4 - 0s - loss: 0.5588 - accuracy: 0.3839 - 12ms/epoch - 3ms/step
Epoch 10/100
4/4 - 0s - loss: 0.5471 - accuracy: 0.4018 - 8ms/epoch - 2ms/step
Epoch 11/100
4/4 - 0s - loss: 0.5360 - accuracy: 0.4018 - 8ms/epoch - 2ms/step
Epoch 12/100
4/4 - 0s - loss: 0.5252 - accuracy: 0.4107 - 15ms/epoch - 4ms/step
Epoch 13/100
4/4 - 0s - loss: 0.5142 - accuracy: 

In [15]:
loss, accuracy = model.evaluate(x_test_scaled, y_test, verbose=0)
print("Test Accuracy:", accuracy)

Test Accuracy: 0.6842105388641357
